# Generated by Django 5.1.6 on 2025-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
